name: juchari_uandakua
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  #Control de estados
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  #Inyección de dependencias
  get_it: ^9.2.0
  
  #Navegación
  go_router: ^17.0.1
  
  #Bases de datos
  sqflite: ^2.4.2

  #Manejo de rutas
  path: ^1.9.1
  path_provider: ^2.1.5

  #Networking
  dio: ^5.9.1
  connectivity_plus: ^7.0.0

  #Serializacion
  json_annotation: ^4.10.0
  collection: ^1.19.1
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
